#!/usr/bin/env python

import roslib; roslib.load_manifest('pr2_delivery')
import rospy
import pr2_delivery

if __name__ == '__main__':
    rospy.init_node('deliver_server')
    server = pr2_delivery.DeliverServer()
    rospy.spin()
